<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ImportDataMurid extends Seeder
{
    public function run(): void
    {
        // === Insert Kelas ===
        DB::table('kelas')->insert([
            ['id' => 1, 'nama_kelas' => '9A'],
            ['id' => 2, 'nama_kelas' => '9B'],
            ['id' => 3, 'nama_kelas' => '9C'],
        ]);

        // === Insert Murid ===
        DB::table('murid')->insert([
            [
                'nipd' => '7654',
                'gambar' => null,
                'kelas_id' => 1,
                'nama' => 'Abdul Latif',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 1,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '7661',
                'gambar' => null,
                'kelas_id' => 1,
                'nama' => 'ADHWA NABILAH',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 2,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '7662',
                'gambar' => null,
                'kelas_id' => 1,
                'nama' => 'ADIT SAPUTRA',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 3,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '7670',
                'gambar' => null,
                'kelas_id' => 1,
                'nama' => 'Ahmad Raffi Setiawan',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 4,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '7683',
                'gambar' => null,
                'kelas_id' => 1,
                'nama' => 'Alina Maulida',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 5,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '7690',
                'gambar' => null,
                'kelas_id' => 1,
                'nama' => 'ANISSA NAZWA',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 6,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '7691',
                'gambar' => null,
                'kelas_id' => 1,
                'nama' => 'AQLI NORJAWAD',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 7,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '7701',
                'gambar' => null,
                'kelas_id' => 1,
                'nama' => 'Cindy Agustina',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 8,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '7705',
                'gambar' => null,
                'kelas_id' => 1,
                'nama' => 'Davit Alinskie',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 9,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '7714',
                'gambar' => null,
                'kelas_id' => 1,
                'nama' => 'Emilda',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 10,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '7731',
                'gambar' => null,
                'kelas_id' => 1,
                'nama' => 'KHAIRUNISA AZ-ZAHRA',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 11,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '7737',
                'gambar' => null,
                'kelas_id' => 1,
                'nama' => 'M. FIRDAUS',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 12,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '7744',
                'gambar' => null,
                'kelas_id' => 1,
                'nama' => 'M. Habibi',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 13,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '7747',
                'gambar' => null,
                'kelas_id' => 1,
                'nama' => 'MALIKA NUR AULIA',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 14,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '7770',
                'gambar' => null,
                'kelas_id' => 1,
                'nama' => 'MUHAMAD HABIBI',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 15,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '7757',
                'gambar' => null,
                'kelas_id' => 1,
                'nama' => 'MUHAMMAD AKBAR ANUGERAH',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 16,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '7764',
                'gambar' => null,
                'kelas_id' => 1,
                'nama' => 'MUHAMMAD DIRGA',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 17,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '8354',
                'gambar' => null,
                'kelas_id' => 1,
                'nama' => 'MUHAMMAD NAJMI ADITAMA',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 18,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '7777',
                'gambar' => null,
                'kelas_id' => 1,
                'nama' => 'Muhammad Nasir',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 19,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '7784',
                'gambar' => null,
                'kelas_id' => 1,
                'nama' => 'Muhammad Reyhan Fadhilla',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 20,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '7792',
                'gambar' => null,
                'kelas_id' => 1,
                'nama' => 'MUHAMMAD SAUGI',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 21,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '7797',
                'gambar' => null,
                'kelas_id' => 1,
                'nama' => 'NABILA RAMADHANISA',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 22,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '7804',
                'gambar' => null,
                'kelas_id' => 1,
                'nama' => 'Nayla Kamilah',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 23,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '7812',
                'gambar' => null,
                'kelas_id' => 1,
                'nama' => 'Nova Tri Adiastuti',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 24,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '8099',
                'gambar' => null,
                'kelas_id' => 1,
                'nama' => 'NUR APRILIA HASANAH',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 25,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '7819',
                'gambar' => null,
                'kelas_id' => 1,
                'nama' => 'NURYASMINE',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 26,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '7825',
                'gambar' => null,
                'kelas_id' => 1,
                'nama' => 'Rafli Abdillah',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 27,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '7834',
                'gambar' => null,
                'kelas_id' => 1,
                'nama' => 'Risa Amelia',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 28,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '7839',
                'gambar' => null,
                'kelas_id' => 1,
                'nama' => 'Royandi Fadilah',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 29,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '7849',
                'gambar' => null,
                'kelas_id' => 1,
                'nama' => 'Sevia Rahmadina',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 30,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '7856',
                'gambar' => null,
                'kelas_id' => 1,
                'nama' => 'Syafa Maulida',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 31,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '7864',
                'gambar' => null,
                'kelas_id' => 1,
                'nama' => 'VINA INDERIYANI',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 32,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '7869',
                'gambar' => null,
                'kelas_id' => 1,
                'nama' => 'ZAINI',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 33,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '7655',
                'gambar' => null,
                'kelas_id' => 2,
                'nama' => 'Abdul Majid',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 1,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '7671',
                'gambar' => null,
                'kelas_id' => 2,
                'nama' => 'AHMAD RAMADANI',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 2,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '7676',
                'gambar' => null,
                'kelas_id' => 2,
                'nama' => 'AINUR RAMADHANI',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 3,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '7684',
                'gambar' => null,
                'kelas_id' => 2,
                'nama' => 'ALMIRA NURGITA ZULKARNAIN',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 4,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '8100',
                'gambar' => null,
                'kelas_id' => 2,
                'nama' => 'Arjuna Adi Nugroho',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 5,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '7692',
                'gambar' => null,
                'kelas_id' => 2,
                'nama' => 'ARKAN PUTRA',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 6,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '7702',
                'gambar' => null,
                'kelas_id' => 2,
                'nama' => 'CYNTIA FEBRIONA',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 7,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '7707',
                'gambar' => null,
                'kelas_id' => 2,
                'nama' => 'Dimas',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 8,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '7719',
                'gambar' => null,
                'kelas_id' => 2,
                'nama' => 'Gilang',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 9,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '7721',
                'gambar' => null,
                'kelas_id' => 2,
                'nama' => 'GUSTI NUR SAFA',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 10,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '7732',
                'gambar' => null,
                'kelas_id' => 2,
                'nama' => 'KHANSAA NOOR ALODIA',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 11,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '7745',
                'gambar' => null,
                'kelas_id' => 2,
                'nama' => 'M. Hafis Fahreza',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 12,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '7738',
                'gambar' => null,
                'kelas_id' => 2,
                'nama' => 'M. INDRA PRATAMA',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 13,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '7748',
                'gambar' => null,
                'kelas_id' => 2,
                'nama' => 'Mariatul',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 14,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '8353',
                'gambar' => null,
                'kelas_id' => 2,
                'nama' => 'MOZA NUR SYAIRA',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 15,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '7758',
                'gambar' => null,
                'kelas_id' => 2,
                'nama' => 'MUHAMMAD AKEYLA',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 16,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '7765',
                'gambar' => null,
                'kelas_id' => 2,
                'nama' => 'Muhammad Fahri',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 17,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '7771',
                'gambar' => null,
                'kelas_id' => 2,
                'nama' => 'MUHAMMAD HIRDY',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 18,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '7778',
                'gambar' => null,
                'kelas_id' => 2,
                'nama' => 'MUHAMMAD RAFFALI MIRZA',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 19,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '7785',
                'gambar' => null,
                'kelas_id' => 2,
                'nama' => 'MUHAMMAD REZA',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 20,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '7793',
                'gambar' => null,
                'kelas_id' => 2,
                'nama' => 'MUHAMMAD SULTAN PRADANA',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 21,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '7798',
                'gambar' => null,
                'kelas_id' => 2,
                'nama' => 'Nadia',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 22,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '7805',
                'gambar' => null,
                'kelas_id' => 2,
                'nama' => 'Nor Asich',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 23,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '7813',
                'gambar' => null,
                'kelas_id' => 2,
                'nama' => 'NOVIA MAYANTI',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 24,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '7820',
                'gambar' => null,
                'kelas_id' => 2,
                'nama' => 'Nuviana Safitri',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 25,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '7827',
                'gambar' => null,
                'kelas_id' => 2,
                'nama' => 'RAMADHAN',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 26,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '7835',
                'gambar' => null,
                'kelas_id' => 2,
                'nama' => 'RISKA KHAIRINA',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 27,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '7840',
                'gambar' => null,
                'kelas_id' => 2,
                'nama' => 'ROYHAN SAPUTRA',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 28,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '7845',
                'gambar' => null,
                'kelas_id' => 2,
                'nama' => 'SALIMAH',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 29,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '7850',
                'gambar' => null,
                'kelas_id' => 2,
                'nama' => 'Shafa Zakia',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 30,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '7858',
                'gambar' => null,
                'kelas_id' => 2,
                'nama' => 'Syarifah Nur',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 31,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '7865',
                'gambar' => null,
                'kelas_id' => 2,
                'nama' => 'YASMIN',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 32,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '7871',
                'gambar' => null,
                'kelas_id' => 2,
                'nama' => 'Ziggy Saverio Danadyaksa',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 33,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '7656',
                'gambar' => null,
                'kelas_id' => 3,
                'nama' => 'ABDUL SAMAN',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 1,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '7665',
                'gambar' => null,
                'kelas_id' => 3,
                'nama' => 'Adya Widjanuar',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 2,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '7685',
                'gambar' => null,
                'kelas_id' => 3,
                'nama' => 'Amelia Fazarina',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 3,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '7694',
                'gambar' => null,
                'kelas_id' => 3,
                'nama' => 'AULIA AUFA',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 4,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '7696',
                'gambar' => null,
                'kelas_id' => 3,
                'nama' => 'BAHRUL ILMI',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 5,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '7708',
                'gambar' => null,
                'kelas_id' => 3,
                'nama' => 'Dina Laras',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 6,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '7711',
                'gambar' => null,
                'kelas_id' => 3,
                'nama' => 'DODDY SANJAYA',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 7,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '8109',
                'gambar' => null,
                'kelas_id' => 3,
                'nama' => 'Egi Prasetya Apandi',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 8,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '7720',
                'gambar' => null,
                'kelas_id' => 3,
                'nama' => 'Giyan Noor',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 9,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '7751',
                'gambar' => null,
                'kelas_id' => 3,
                'nama' => 'H. Mohammad Maulidan',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 10,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '7725',
                'gambar' => null,
                'kelas_id' => 3,
                'nama' => 'HERLINA FITRI',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 11,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '7733',
                'gambar' => null,
                'kelas_id' => 3,
                'nama' => 'KHAZIINATUL SALWA',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 12,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '7739',
                'gambar' => null,
                'kelas_id' => 3,
                'nama' => 'M. Lukman Nur Hakim',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 13,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '8101',
                'gambar' => null,
                'kelas_id' => 3,
                'nama' => 'M. ROMDANI',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 14,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '7749',
                'gambar' => null,
                'kelas_id' => 3,
                'nama' => 'Maulidya Aurelian Noor',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 15,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '7759',
                'gambar' => null,
                'kelas_id' => 3,
                'nama' => 'Muhammad Aldi Firdaus',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 16,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '7766',
                'gambar' => null,
                'kelas_id' => 3,
                'nama' => 'Muhammad Farhan Sanjaya',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 17,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '7772',
                'gambar' => null,
                'kelas_id' => 3,
                'nama' => 'MUHAMMAD IHSAN',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 18,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '7779',
                'gambar' => null,
                'kelas_id' => 3,
                'nama' => 'Muhammad Raihan Effendy',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 19,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '7786',
                'gambar' => null,
                'kelas_id' => 3,
                'nama' => 'MUHAMMAD REZA SAPUTRA',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 20,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '7787',
                'gambar' => null,
                'kelas_id' => 3,
                'nama' => 'Muhammad Ridha',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 21,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '7794',
                'gambar' => null,
                'kelas_id' => 3,
                'nama' => 'MUHAMMAD WILDAN',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 22,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '7799',
                'gambar' => null,
                'kelas_id' => 3,
                'nama' => 'NADIA PUTRI',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 23,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '7806',
                'gambar' => null,
                'kelas_id' => 3,
                'nama' => 'NOOR ASSIFA RAMADHANI',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 24,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '7814',
                'gambar' => null,
                'kelas_id' => 3,
                'nama' => 'Nur Atika',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 25,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '7821',
                'gambar' => null,
                'kelas_id' => 3,
                'nama' => 'Putri Paramita',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 26,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '7836',
                'gambar' => null,
                'kelas_id' => 3,
                'nama' => 'Risna Wati',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 27,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '7841',
                'gambar' => null,
                'kelas_id' => 3,
                'nama' => 'RUDIANNOR',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 28,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '7851',
                'gambar' => null,
                'kelas_id' => 3,
                'nama' => 'Shiren Nur Alfarisi',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 29,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '7859',
                'gambar' => null,
                'kelas_id' => 3,
                'nama' => 'Syifa',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 30,
                'password' => bcrypt('smpn11bjm'),
            ],
            [
                'nipd' => '7866',
                'gambar' => null,
                'kelas_id' => 3,
                'nama' => 'YOVELA GABY SIAHAAN',
                'sekolah' => 'SMP NEGERI 11 BANJARMASIN',
                'absen' => 31,
                'password' => bcrypt('smpn11bjm'),
            ],
        ]);
    }
}
